security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            provider: our_db_provider
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin/*, roles: ROLE_ADMIN }
        - { path: ^/account/*, roles: IS_AUTHENTICATED_REMEMBERED }
