homepage:
    path: /
    methods: [GET]
    defaults: { _controller: 'App\Controller\IndexController::homepage' }

login:
    path: /login
    defaults: { _controller: 'App\Controller\SecurityController::login' }

logout:
    path: /logout

register_en:
    path: /register
    host: www.unplugged.co.uk
    defaults: { _controller: 'App\Controller\Account\RegisterController::register' }
register_nl:
    path: /registreren
    host: www.unplugged.nl
    defaults: { _controller: 'App\Controller\Account\RegisterController::register' }

registered_en:
    path: /registered
    host: www.unplugged.co.uk
    defaults: { _controller: 'App\Controller\Account\RegisterController::registered' }
registered_nl:
    path: /geregistreerd
    host: www.unplugged.nl
    defaults: { _controller: 'App\Controller\Account\RegisterController::registered' }

admin_dashboard:
    path: /admin/
    methods: [GET]
    defaults: { _controller: 'App\Controller\DashboardController::dashboard' }

account:
    path: /account
    methods: [GET]
    defaults: { _controller: 'App\Controller\Account\AccountController::account' }

account_edit_en:
    path: /edit-account
    host: www.unplugged.co.uk
    defaults: { _controller: 'App\Controller\Account\EditController::edit' }
account_edit_nl:
    path: /wijzig-account
    host: www.unplugged.nl
    defaults: { _controller: 'App\Controller\Account\EditController::edit' }

forgot_password_en:
    path: /forgot-password
    host: www.unplugged.co.uk
    defaults: { _controller: 'App\Controller\SecurityController::forgotPassword' }
forgot_password_nl:
    path: /wachtwoord-vergeten
    host: www.unplugged.nl
    defaults: { _controller: 'App\Controller\SecurityController::forgotPassword' }

reset_password_en:
    path: /reset-password
    host: www.unplugged.co.uk
    defaults: { _controller: 'App\Controller\SecurityController::resetPassword' }
reset_password_nl:
    path: /wachtwoord-opnieuw-instellen
    host: www.unplugged.nl
    defaults: { _controller: 'App\Controller\SecurityController::resetPassword' }

contact:
    path: /contact
    defaults: { _controller: 'App\Controller\ContactController::contact' }

magnesium_test:
    path: /magnesium-test
    defaults: { _controller: 'App\Controller\Test\MagnesiumTestController::test' }

vitamin_test_en:
    path: /vitamin-b12-test
    host: www.unplugged.co.uk
    defaults: { _controller: 'App\Controller\Test\VitamineTestController::test' }
vitamin_test_nl:
    path: /vitamine-b12-test
    host: www.unplugged.nl
    defaults: { _controller: 'App\Controller\Test\VitamineTestController::test' }

page_view:
    path: /{slug}
    methods: [GET]
    defaults: { _controller: 'App\Controller\Page\PageViewController::view' }