homepage:
    path: /
    methods: [GET]
    defaults: { _controller: 'App\Controller\IndexController::homepage' }

login:
    path: /login
    defaults: { _controller: 'App\Controller\SecurityController::login' }

logout:
    path: /logout

register_en:
    path: /register
    host: www.unplugged.co.uk
    defaults: { _controller: 'App\Controller\Account\RegisterController::register' }
register_nl:
    path: /registreren
    host: www.unplugged.nl
    defaults: { _controller: 'App\Controller\Account\RegisterController::register' }

registered_en:
    path: /registered
    host: www.unplugged.co.uk
    defaults: { _controller: 'App\Controller\Account\RegisterController::registered' }
registered_nl:
    path: /geregistreerd
    host: www.unplugged.nl
    defaults: { _controller: 'App\Controller\Account\RegisterController::registered' }

admin_dashboard:
    path: /admin/
    methods: [GET]
    defaults: { _controller: 'App\Controller\DashboardController::dashboard' }

account:
    path: /account
    methods: [GET]
    defaults: { _controller: 'App\Controller\Account\AccountController::account' }

forgot-password_en:
    path: /forgot-password
    host: www.unplugged.co.uk
    defaults: { _controller: 'App\Controller\SecurityController::forgotPassword' }
forgot-password_nl:
    path: /wachtwoord-vergeten
    host: www.unplugged.nl
    defaults: { _controller: 'App\Controller\SecurityController::forgotPassword' }

reset-password_en:
    path: /reset-password
    host: www.unplugged.co.uk
    defaults: { _controller: 'App\Controller\SecurityController::resetPassword' }
reset-password_nl:
    path: /wachtwoord-opnieuw-instellen
    host: www.unplugged.nl
    defaults: { _controller: 'App\Controller\SecurityController::resetPassword' }

contact:
    path: /contact
    defaults: { _controller: 'App\Controller\ContactController::contact' }

page_view:
    path: /{slug}
    methods: [GET]
    defaults: { _controller: 'App\Controller\Page\PageViewController::view' }